[workspace]
members = ["crates/api", "crates/core/domain", "crates/core/infrastructure"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.99"
async-trait = "0.1.89"
futures = "0.3.31"
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "tls-rustls",
  "macros",
  "postgres",
  "chrono",
  "migrate",
] }
thiserror = "2.0.16"
tracing = { version = "0.1.41", features = ["log"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true
