services:
  rustatsu:
    image: abduzzy/rustatsu-sync:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE__HOST=postgresql
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=password
      - DATABASE__DATABASE_NAME=rustatsu
      # - APPLICATION__PORT=8080
      # - APPLICATION__HOST=0.0.0.0
      # - APPLICATION__ALLOW_REGISTRATION=true
      # - APPLICATION__RUN_MIGRATION=TRUE
      # - JWT__SECRET=my-secret-key
      # - JWT__ISS=rustatsu
      # - JWT__AUD=rustatsu
      - RUST_LOG=warn
    restart: always
    depends_on:
      - postgresql
  postgresql:
    image: postgres:17.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustatsu
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
