database:
  username: kotatsu
  password: kotatsu
  database_name: kotatsu
  host: 127.0.0.1
  port: 3307
application:
  port: 8000
  host: 127.0.0.1
  allow_registration: true
jwt:
  secret: "jwt-is-super-awesome"
  iss: "rustatsu"
  aud: "rustatsu"
